### ISSUE TITLE
make update_modules_list fail when no X server

### ISSUE THREAD

**Issue by gaetancollaud** [lwinkler/markus#7]
Hi,

I'm trying to make a docker image of markus. But when I execute the command `make update_modules_list` I have the error below : 
```
libdc1394 error: Failed to initialize libdc1394
2015-10-30 20:40:16,077 [0x7f442fac6a40] INFO  [main] Using default configuration file config.xml
2015-10-30 20:40:16,077 [0x7f442fac6a40] INFO  [main] Markus version 1.3.7.1-4-gef631c1-dirty, compiled with Opencv 2.4.8, vp-detection modules version 1.3.7.1-4-gef631c1-dirty, built on Linux f31b2c4026e4 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
markus: cannot connect to X server 
```

The _update_modules_list_ target trigger the command `markus -d`. I tried to add the `-n` argument for _no-gui_ but nothing changed.

Then I had a look at the code and I see that in [main.cpp line 375](https://github.com/lwinkler/markus/blob/master/main.cpp#L375-L379) you skipped everything (including the no-gui parameter) when you build the module list.

Is there any way to update the module list without any GUI ?

Regards

**Comment by lwinkler** [comment]
Yes there is. You can disable a flag and compile without GUI. 

Using command:
``` 
ccmake . 
```
You should set:

```
 Markus_NO_GUI                    ON                  
```

**Comment by gaetancollaud** [comment]
I put the _Markus_NO_GUI_ flag to _true_ but I still have the same error when generating the modules list. Another idea ?

**Comment by gaetancollaud** [comment]
Never mind, I updated my fork with your repo and it works now.
